[package]
name = "day2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parse-display = "0.5.0"
pretty_env_logger = "0.4.0"
log = "0.4.14"
anyhow = "1.0.41"
pretty_assertions = "0.7.2"
